// <auto-generated>
// Generated from the live RoleAction table (jaftim-local-db, 2026-09-21). One constant per ActionId.
// Regenerate with tools/gen-permissions.ps1 when RoleAction changes; never hand-edit values.
// The value is RoleAction.ActionId - the same id RoleActionMapping and the stored
// procedures (e.g. StockGetById 626/627/628 scope checks) use.
// </auto-generated>
namespace Jaftim.Domain.Security;

/// <summary>
/// The permission catalog. Each constant is a RoleAction.ActionId. Authorization in the API is
/// [HasPermission(Permissions.X)] which is resolved against RoleActionMapping for the caller RoleId.
/// </summary>
public static class Permissions
{
    /// <summary>Auth (_CSS_1)</summary>
    public const int Auth = 1;
    /// <summary>Auth Table (_CSS_2, /authfilter/getdllauthtablevalues)</summary>
    public const int AuthTable = 2;
    /// <summary>Auth Data (_CSS_3, /authfilter/getauthdata)</summary>
    public const int AuthData = 3;
    /// <summary>Customer (_CSS_100)</summary>
    public const int Customer = 100;
    /// <summary>Customer Listing (_CSS_101, /customer/customergetall)</summary>
    public const int CustomerListing = 101;
    /// <summary>Customer Create (_CSS_102, /customer/customersave)</summary>
    public const int CustomerCreate = 102;
    /// <summary>Customer Detail (_CSS_103, /customer/customerdetail)</summary>
    public const int CustomerDetail = 103;
    /// <summary>Customer Stock Allocation (_CSS_104, /customer/stockallocationbycustomer)</summary>
    public const int CustomerStockAllocation = 104;
    /// <summary>Customer Stock Allocation History (_CSS_105, /customer/stockallocationhistorySave)</summary>
    public const int CustomerStockAllocationHistory = 105;
    /// <summary>Customer Section (_CSS_106, /customer/customersectiongetbyid)</summary>
    public const int CustomerSection = 106;
    /// <summary>Employee (_CSS_200)</summary>
    public const int Employee = 200;
    /// <summary>Employee Listing (_CSS_201, /user/usergetall)</summary>
    public const int EmployeeListing = 201;
    /// <summary>Employee Create (_CSS_202, /user/usersave)</summary>
    public const int EmployeeCreate = 202;
    /// <summary>Employee Detail (_CSS_203, /user/userdetail)</summary>
    public const int EmployeeDetail = 203;
    /// <summary>Employee Section (_CSS_204, /user/employeesectiongetbyid)</summary>
    public const int EmployeeSection = 204;
    /// <summary>Role (_CSS_300)</summary>
    public const int Role = 300;
    /// <summary>Role Listing (_CSS_301, /user/rolesgetall)</summary>
    public const int RoleListing = 301;
    /// <summary>Role Save/Edit (_CSS_302, /user/rolesave)</summary>
    public const int RoleSaveEdit = 302;
    /// <summary>Assign Roles (_CSS_304, /user/assignroles)</summary>
    public const int AssignRoles = 304;
    /// <summary>Stock (_CSS_400)</summary>
    public const int Stock = 400;
    /// <summary>Stock Edit (_CSS_401, /stock/stockdetailsave)</summary>
    public const int StockEdit = 401;
    /// <summary>Stock Feature (_CSS_402, /stock/stockfeaturesave)</summary>
    public const int StockFeature = 402;
    /// <summary>Stock File (_CSS_403, /stock/stockdocumentsbyfolderid)</summary>
    public const int StockFile = 403;
    /// <summary>Stock Reservation (_CSS_404, /stock/stockreservationdetailsave)</summary>
    public const int StockReservation = 404;
    /// <summary>Stock Status (_CSS_405, /stock/stockstatussave)</summary>
    public const int StockStatus = 405;
    /// <summary>Stock Refund (_CSS_406, /stock/stockrefundsave)</summary>
    public const int StockRefund = 406;
    /// <summary>Stock Financial (_CSS_407, /stock/stockfinancialsave)</summary>
    public const int StockFinancial = 407;
    /// <summary>Stock Inspection (_CSS_408, /stock/stockinspectionsave)</summary>
    public const int StockInspection = 408;
    /// <summary>Stock File Upload (_CSS_409, /stock/stockfilesave)</summary>
    public const int StockFileUpload = 409;
    /// <summary>Stock Sections (_CSS_410, /stock/stocksectiongetbyid)</summary>
    public const int StockSections = 410;
    /// <summary>Stock Port (_CSS_411, /stock/stockportdetailsave)</summary>
    public const int StockPort = 411;
    /// <summary>Stock BL (_CSS_412, /stock/stockbldetailsave)</summary>
    public const int StockBL = 412;
    /// <summary>Stock Detail (_CSS_413, /stock/stockdetail)</summary>
    public const int StockDetail = 413;
    /// <summary>Stock Note (_CSS_414, /stock/stockinternalnotegetbyid)</summary>
    public const int StockNote = 414;
    /// <summary>Stock Note Save/Edit (_CSS_415, /stock/stockinternalnotesave)</summary>
    public const int StockNoteSaveEdit = 415;
    /// <summary>Stock Financials (_CSS_416, /stock/stockfinancialgetallbystockid)</summary>
    public const int StockFinancials = 416;
    /// <summary>Stock Listing (_CSS_417, /stock)</summary>
    public const int StockListing = 417;
    /// <summary>Stock Shipment Detail (_CSS_418, /stock/stockshipmentdetailsave)</summary>
    public const int StockShipmentDetail = 418;
    /// <summary>Stock Save (_CSS_419, /stock/stocksave)</summary>
    public const int StockSave = 419;
    /// <summary>Stock Specification (_CSS_420, /stock/stockspecificationsave)</summary>
    public const int StockSpecification = 420;
    /// <summary>Stock Shipment Party (_CSS_421, /stock/stockshipmentpartysave)</summary>
    public const int StockShipmentParty = 421;
    /// <summary>Stock Cost Detail (_CSS_422, /stock/stockcostdetailsave)</summary>
    public const int StockCostDetail = 422;
    /// <summary>Stock Weight Dimension (_CSS_423, /stock/stockweightdimensionlsave)</summary>
    public const int StockWeightDimension = 423;
    /// <summary>Stock Price (_CSS_424, /stock/stockpricesave)</summary>
    public const int StockPrice = 424;
    /// <summary>Stock Financial Delete (_CSS_425, /stock/stockfinancialdelete)</summary>
    public const int StockFinancialDelete = 425;
    /// <summary>Stock Courier Info (_CSS_426, /stock/stockcourierinfosave)</summary>
    public const int StockCourierInfo = 426;
    /// <summary>Stock Section (_CSS_427, /stock/stocksectiongetbyid)</summary>
    public const int StockSection = 427;
    /// <summary>Bank Statement (_CSS_500)</summary>
    public const int BankStatement = 500;
    /// <summary>Bank Statment Listing (_CSS_501, /bankstatement)</summary>
    public const int BankStatmentListing = 501;
    /// <summary>Bank Reconcilation (_CSS_502, /bankStatement/bankstatementreconcilation)</summary>
    public const int BankReconcilation = 502;
    /// <summary>Bank Statement Upload (_CSS_503, /bankStatement/addstatement)</summary>
    public const int BankStatementUpload = 503;
    /// <summary>Bank Reconcilation Approval (_CSS_504, /bankStatement/bankstatementreconcilationapproval)</summary>
    public const int BankReconcilationApproval = 504;
    /// <summary>Income (_CSS_520)</summary>
    public const int Income = 520;
    /// <summary>Income Reconcilation Listing (_CSS_521, /bankStatement/incomereconcilationgetall)</summary>
    public const int IncomeReconcilationListing = 521;
    /// <summary>Income Reconcilation (_CSS_522, /bankStatement/incomereconcilation)</summary>
    public const int IncomeReconcilation = 522;
    /// <summary>Customer Edit (_CSS_523, /customer/customersave)</summary>
    public const int CustomerEdit = 523;
    /// <summary>My Task (_CSS_524, /user/mytask)</summary>
    public const int MyTask = 524;
    /// <summary>Customer Wallet Conversions (_CSS_525, /customer/getallwalletconversion)</summary>
    public const int CustomerWalletConversions = 525;
    /// <summary>Customer Tagging (_CSS_526)</summary>
    public const int CustomerTaggingModule = 526;
    /// <summary>Stock Tab Images (_CSS_527, Stock/StockDetail)</summary>
    public const int StockTabImages = 527;
    /// <summary>Stock Tab Overview (_CSS_528, Stock/StockDetail)</summary>
    public const int StockTabOverview = 528;
    /// <summary>Stock Tab Reservation Bids (_CSS_529, Stock/StockDetail)</summary>
    public const int StockTabReservationBids = 529;
    /// <summary>Stock Tab Reservation (_CSS_530, Stock/StockDetail)</summary>
    public const int StockTabReservation = 530;
    /// <summary>Stock Tab Cost (_CSS_531, Stock/StockDetail)</summary>
    public const int StockTabCost = 531;
    /// <summary>Stock Tab Inspection (_CSS_532, Stock/StockDetail)</summary>
    public const int StockTabInspection = 532;
    /// <summary>Stock Tab Shipment (_CSS_533, Stock/StockDetail)</summary>
    public const int StockTabShipment = 533;
    /// <summary>Stock Tab Documents (_CSS_534, Stock/StockDetail)</summary>
    public const int StockTabDocuments = 534;
    /// <summary>Stock Tab Internal Notes (_CSS_535, Stock/StockDetail)</summary>
    public const int StockTabInternalNotes = 535;
    /// <summary>Stock Tab Status (_CSS_536, Stock/StockDetail)</summary>
    public const int StockTabStatus = 536;
    /// <summary>Inquiry (_CSS_537, /Inquiry/InquiryGetAll)</summary>
    public const int Inquiry = 537;
    /// <summary>Inquiry Listing (_CSS_538)</summary>
    public const int InquiryListing = 538;
    /// <summary>Inquiry Save (_CSS_539)</summary>
    public const int InquirySave = 539;
    /// <summary>Sales (_CSS_540)</summary>
    public const int Sales = 540;
    /// <summary>Customer Tab My Profile (_CSS_541)</summary>
    public const int CustomerTabMyProfile = 541;
    /// <summary>Customer Tab My Reservation (_CSS_542)</summary>
    public const int CustomerTabMyReservation = 542;
    /// <summary>Customer Tab Wallet Conversion (_CSS_543)</summary>
    public const int CustomerTabWalletConversion = 543;
    /// <summary>Customer Tab Purchase History (_CSS_544)</summary>
    public const int CustomerTabPurchaseHistory = 544;
    /// <summary>Customer Tab Cancellation History (_CSS_545)</summary>
    public const int CustomerTabCancellationHistory = 545;
    /// <summary>Customer Tab Inquiries (_CSS_546)</summary>
    public const int CustomerTabInquiries = 546;
    /// <summary>Customer Tab Customer Remarks (_CSS_547)</summary>
    public const int CustomerTabCustomerRemarks = 547;
    /// <summary>User Hierarchy (_CSS_548)</summary>
    public const int UserHierarchy = 548;
    /// <summary>Reporting Module (_CSS_549)</summary>
    public const int ReportingModule = 549;
    /// <summary>Customer Tagging (_CSS_550)</summary>
    public const int CustomerTagging = 550;
    /// <summary>Tagged History (_CSS_551)</summary>
    public const int TaggedHistory = 551;
    /// <summary>UnTagged History (_CSS_552)</summary>
    public const int UnTaggedHistory = 552;
    /// <summary>Cannot Tag Customer (_CSS_553)</summary>
    public const int CannotTagCustomer = 553;
    /// <summary>Customer Tab Consignee (_CSS_554)</summary>
    public const int CustomerTabConsignee = 554;
    /// <summary>Customer Tab Notify Party (_CSS_555)</summary>
    public const int CustomerTabNotifyParty = 555;
    /// <summary>Customer Tab Courier (_CSS_556)</summary>
    public const int CustomerTabCourier = 556;
    /// <summary>Stock Activity (_CSS_557, Stock/StockDetail)</summary>
    public const int StockActivity = 557;
    /// <summary>Stock Export (_CSS_558, Stock/Index)</summary>
    public const int StockExport = 558;
    /// <summary>Customer Statement (_CSS_559, /customer/customerdetail)</summary>
    public const int CustomerStatement = 559;
    /// <summary>Consginee Tab (_CSS_560, /Stock/StockDetail)</summary>
    public const int ConsgineeTab = 560;
    /// <summary>Stock Cost Edit/Save (_CSS_561, /Stock/StockDetail)</summary>
    public const int StockCostEditSave = 561;
    /// <summary>Customer Adjustment (_CSS_562, /customer/customerdetail)</summary>
    public const int CustomerAdjustment = 562;
    /// <summary>Reservation Edit (_CSS_563, Stock/StockDetail)</summary>
    public const int ReservationEdit = 563;
    /// <summary>Purchased Stock View (_CSS_564)</summary>
    public const int PurchasedStockView = 564;
    /// <summary>Pre-Departure Stock View (_CSS_565)</summary>
    public const int PreDepartureStockView = 565;
    /// <summary>In Transit Stock View (_CSS_566)</summary>
    public const int InTransitStockView = 566;
    /// <summary>In Garage Stock View (_CSS_567)</summary>
    public const int InGarageStockView = 567;
    /// <summary>Ready for Sale Stock View (_CSS_568)</summary>
    public const int ReadyForSaleStockView = 568;
    /// <summary>Avaialble for Sale Stock View (_CSS_569)</summary>
    public const int AvaialbleForSaleStockView = 569;
    /// <summary>Sold Stock View (_CSS_570)</summary>
    public const int SoldStockView = 570;
    /// <summary>Not Sold Stock View (_CSS_571)</summary>
    public const int NotSoldStockView = 571;
    /// <summary>Archive Stock View (_CSS_572)</summary>
    public const int ArchiveStockView = 572;
    /// <summary>Warehouse Stock View (_CSS_573)</summary>
    public const int WarehouseStockView = 573;
    /// <summary>Stock Journey Status (_CSS_574)</summary>
    public const int StockJourneyStatus = 574;
    /// <summary>In Garage (_CSS_575)</summary>
    public const int InGarage = 575;
    /// <summary>Not Sold (Admin Only) (_CSS_576)</summary>
    public const int NotSoldAdminOnly = 576;
    /// <summary>Pricing Module (_CSS_577)</summary>
    public const int PricingModule = 577;
    /// <summary>Stock Deallocation (_CSS_578, /customer/customerdetail)</summary>
    public const int StockDeallocation = 578;
    /// <summary>Forfeit Customer Balance (_CSS_579, /customer/customerbalanceforfeituresave)</summary>
    public const int ForfeitCustomerBalance = 579;
    /// <summary>Add Financials (_CSS_580, /stock/stockdetail)</summary>
    public const int AddFinancials = 580;
    /// <summary>Release Forfeited Balance (_CSS_581, /customer/customerbalanceforfeiturereleasesave)</summary>
    public const int ReleaseForfeitedBalance = 581;
    /// <summary>Document Module (_CSS_590, /document/index)</summary>
    public const int DocumentModule = 590;
    /// <summary>Document - Draft BL (_CSS_591)</summary>
    public const int DocumentDraftBL = 591;
    /// <summary>Document - OBL (_CSS_592)</summary>
    public const int DocumentOBL = 592;
    /// <summary>Document - Inspection (_CSS_593)</summary>
    public const int DocumentInspection = 593;
    /// <summary>Document - DHL (_CSS_594)</summary>
    public const int DocumentDHL = 594;
    /// <summary>Document - Invoice (_CSS_595)</summary>
    public const int DocumentInvoice = 595;
    /// <summary>Document - Repair Bills (_CSS_596)</summary>
    public const int DocumentRepairBills = 596;
    /// <summary>Document - DHL Tracking (_CSS_597, /document/savetracking)</summary>
    public const int DocumentDHLTracking = 597;
    /// <summary>Document - Export Certificate (_CSS_598)</summary>
    public const int DocumentExportCertificate = 598;
    /// <summary>Shipping - Freight Status (_CSS_599, /shipping/savefreightstatus)</summary>
    public const int ShippingFreightStatus = 599;
    /// <summary>Request Stock Deallocation (_CSS_600, /customer/stockdeallocationsave)</summary>
    public const int RequestStockDeallocation = 600;
    /// <summary>Direct Stock Deallocation (_CSS_601, /customer/stockdeallocationsave)</summary>
    public const int DirectStockDeallocation = 601;
    /// <summary>Review Stock Deallocation (_CSS_602, /customer/deallocationrequestapprovalsave)</summary>
    public const int ReviewStockDeallocation = 602;
    /// <summary>Inspection Module (_CSS_603, /inspection/index)</summary>
    public const int InspectionModule = 603;
    /// <summary>Inspection - Update Result (_CSS_604, /inspection/save)</summary>
    public const int InspectionUpdateResult = 604;
    /// <summary>Vendor Module (_CSS_605, /vendor/index)</summary>
    public const int VendorModule = 605;
    /// <summary>Vendor - Create Vendor (_CSS_606, /vendor/savevendor)</summary>
    public const int VendorCreateVendor = 606;
    /// <summary>Vendor - Create Job (_CSS_607, /vendor/savejob)</summary>
    public const int VendorCreateJob = 607;
    /// <summary>Inquiry - Contact Edit Save (_CSS_608)</summary>
    public const int InquiryContactEditSave = 608;
    /// <summary>Vendor - Settle Payment (_CSS_609, /vendor/savesettlement)</summary>
    public const int VendorSettlePayment = 609;
    /// <summary>Shipping - Complete Schedule (_CSS_610, /shipping/complete)</summary>
    public const int ShippingCompleteSchedule = 610;
    /// <summary>Shipping Module (_CSS_611, /shipping/index)</summary>
    public const int ShippingModule = 611;
    /// <summary>My Task - Remittances (_CSS_612, /user/remittancerequests)</summary>
    public const int MyTaskRemittances = 612;
    /// <summary>My Task - Currency Conversions (_CSS_613, /customer/getallwalletconversion)</summary>
    public const int MyTaskCurrencyConversions = 613;
    /// <summary>My Task - Refunds (_CSS_614, /customer/getpendingrefundrequests)</summary>
    public const int MyTaskRefunds = 614;
    /// <summary>My Task - Adjustments/Waivers (_CSS_615, /customer/getadjustmentrequests)</summary>
    public const int MyTaskAdjustmentsWaivers = 615;
    /// <summary>My Task - Deallocations (_CSS_616, /customer/getdeallocationrequests)</summary>
    public const int MyTaskDeallocations = 616;
    /// <summary>My Task - Discount Requests (_CSS_617, /stock/stockgetdiscountrequests)</summary>
    public const int MyTaskDiscountRequests = 617;
    /// <summary>My Task - Shipping Requests (_CSS_618, /user/shippingrequests)</summary>
    public const int MyTaskShippingRequests = 618;
    /// <summary>Consignee Edit (_CSS_619, /stock/stockshipmentpartysave)</summary>
    public const int ConsigneeEdit = 619;
    /// <summary>Notify Party Edit (_CSS_620, /stock/stockshipmentpartysave)</summary>
    public const int NotifyPartyEdit = 620;
    /// <summary>Customer Wallet Transfer (_CSS_621)</summary>
    public const int CustomerWalletTransfer = 621;
    /// <summary>Request Customer Wallet Transfer (_CSS_622, /customer/customerwallettransferrequestsave)</summary>
    public const int RequestCustomerWalletTransfer = 622;
    /// <summary>Review Customer Wallet Transfer (_CSS_623, /customer/customerwallettransferapprovalsave)</summary>
    public const int ReviewCustomerWalletTransfer = 623;
    /// <summary>My Task - Wallet Transfers (_CSS_624, /customer/getcustomerwallettransfers)</summary>
    public const int MyTaskWalletTransfers = 624;
    /// <summary>Direct Customer Wallet Transfer (_CSS_625, /customer/customerwallettransferrequestsave)</summary>
    public const int DirectCustomerWalletTransfer = 625;
    /// <summary>Reserved Stock Detail - Self Access (_CSS_626)</summary>
    public const int ReservedStockDetailSelfAccess = 626;
    /// <summary>Reserved Stock Detail - Team Scope (_CSS_627)</summary>
    public const int ReservedStockDetailTeamScope = 627;
    /// <summary>Reserved Stock Detail - All Scope (_CSS_628)</summary>
    public const int ReservedStockDetailAllScope = 628;
    /// <summary>Customer Tab Conversation Logs (_CSS_629, /customer/customerconversationlogs)</summary>
    public const int CustomerTabConversationLogs = 629;
    /// <summary>Australia transport (TransportModule)</summary>
    public const int AustraliaTransport = 630;
    /// <summary>Transport quotations (TransportQuote, /transport/index)</summary>
    public const int TransportQuotations = 631;
    /// <summary>Transport administration (TransportAdmin, /transport/admin)</summary>
    public const int TransportAdministration = 632;
    /// <summary>Operations (_CSS_900)</summary>
    public const int Operations = 900;
    /// <summary>Finance (_CSS_901)</summary>
    public const int Finance = 901;
    /// <summary>People (_CSS_902)</summary>
    public const int People = 902;
    /// <summary>Settings (_CSS_903)</summary>
    public const int Settings = 903;
    /// <summary>Notification Settings (_CSS_904)</summary>
    public const int NotificationSettings = 904;
    /// <summary>Master Data (_CSS_905)</summary>
    public const int MasterData = 905;
    /// <summary>Navigation Settings (_CSS_906)</summary>
    public const int NavigationSettings = 906;
    /// <summary>My Tagging (Agent) (_CSS_907)</summary>
    public const int MyTaggingAgent = 907;
}
