# Regenerates src/Jaftim.Domain/Security/Permissions.cs from the live RoleAction table.
# Usage: ./tools/gen-permissions.ps1 -Server localhost -Database jaftim-local-db                      (integrated auth)
#        ./tools/gen-permissions.ps1 -Server <azure server> -Database <db> -User <u> -Password <p>
param(
    [Parameter(Mandatory)] [string] $Server,
    [Parameter(Mandatory)] [string] $Database,
    [string] $User,
    [string] $Password
)
$query = "SET NOCOUNT ON; SELECT ActionId, ActionName, ActionCssClass, COALESCE(ActionMvcPermission, SPACE(0)) AS Mvc FROM RoleAction ORDER BY ActionId;"

[string[]] $auth = if ($User) { "-U", $User, "-P", $Password } else { "-E" }   # integrated auth for local databases (typed: splatting a bare string breaks sqlcmd)
$rows = & sqlcmd -S $Server -d $Database @auth -Q $query -W -s "|" -h -1 | Where-Object { $_ -and $_ -notmatch "^-" }

$seen = @{}
$lines = @()
$lines += '// <auto-generated>'
$lines += "// Generated from the live RoleAction table ($Database, $(Get-Date -Format yyyy-MM-dd)). One constant per ActionId."
$lines += '// Regenerate with tools/gen-permissions.ps1 when RoleAction changes; never hand-edit values.'
$lines += '// The value is RoleAction.ActionId - the same id RoleActionMapping and the stored'
$lines += '// procedures (e.g. StockGetById 626/627/628 scope checks) use.'
$lines += '// </auto-generated>'
$lines += 'namespace Jaftim.Domain.Security;'
$lines += ''
$lines += '/// <summary>'
$lines += '/// The permission catalog. Each constant is a RoleAction.ActionId. Authorization in the API is'
$lines += '/// [HasPermission(Permissions.X)] which is resolved against RoleActionMapping for the caller RoleId.'
$lines += '/// </summary>'
$lines += 'public static class Permissions'
$lines += '{'

foreach ($row in $rows) {
    $parts = $row -split '\|'
    if ($parts.Count -lt 3) { continue }
    $id = $parts[0].Trim(); $name = $parts[1].Trim(); $css = $parts[2].Trim(); $mvc = if ($parts.Count -gt 3) { $parts[3].Trim() } else { '' }

    $ident = ($name -replace '[^A-Za-z0-9]+', ' ').Trim() -split ' ' | ForEach-Object { if ($_.Length) { $_.Substring(0,1).ToUpper() + $_.Substring(1) } }
    $ident = -join $ident
    if ($ident -match '^[0-9]') { $ident = "_$ident" }
    if ($seen.ContainsKey($ident)) { $ident = "${ident}_$id" }               # a later duplicate name gets its id appended
    if ($ident -eq "CustomerTagging" -and $id -eq "526") { $ident = "CustomerTaggingModule" }   # 526 = module root, 550 = customer-tab action (kept stable for existing code)
    $seen[$ident] = $true

    $suffix = if ($mvc -and $mvc -ne '/') { ", $mvc" } else { '' }
    $lines += "    /// <summary>$name ($css$suffix)</summary>"
    $lines += "    public const int $ident = $id;"
}
$lines += '}'

$target = Join-Path $PSScriptRoot '..\src\Jaftim.Domain\Security\Permissions.cs'
Set-Content -Path $target -Value ($lines -join "`n") -Encoding utf8
Write-Host "Wrote $((Resolve-Path $target).Path) ($($seen.Count) permissions)"
